### ISSUE TITLE
use json serialization

### ISSUE THREAD

**Issue by lemoidului** [Iglesys347/redis-log-handler#21]
Hi,
love it ! great idea to use redis !  
it it possible to use json format in addition to pikle ? 
```
handler = RedisStreamLogHandler(as_pkl=True)
handler = RedisStreamLogHandler(as_json=True)
```
Thanks for the job

**Comment by Iglesys347** [comment]
Hi @lemoidului , thanks four your feedback!
The JSON serialisation option should be available in the version 1.2.0 of the package :wink:
